require ("kucing")
require ("kucing.lazy")
require ("kucing.comp")
require("kucing.telescope")
require("kucing.cyberdream")

vim.cmd('colorscheme cyberdream')
vim.cmd('hi Normal guibg=NONE ctermfg=NONE ctermbg=NONE')
vim.cmd('hi EndOfBuffer guibg=NONE ctermbg=NONE')
vim.cmd('hi LineNr term=BOLD guibg=none guifg=yellow ctermbg=NONE')
